version: '3.8'

services:
  # Development services with nginx proxy
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - VITE_API_BASE_URL=http://localhost/api
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    profiles:
      - dev
    networks:
      - playrook-network
    expose:
      - "3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - GIN_MODE=debug
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    profiles:
      - dev
    networks:
      - playrook-network
    expose:
      - "8080"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    profiles:
      - dev
    networks:
      - playrook-network

networks:
  playrook-network:
    driver: bridge
